#!/usr/bin/env python3
import sys

def openFile(filename):
    try:
        file = open(filename, 'r')
        return file
    except FileNotFoundError:
        print(f"File {filename} not found")
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred: {e}")
        sys.exit(1)

def readEntireFile(filename, mode):
    try:
        with open(filename, mode) as file:
            content = file.read()
            return content
    except FileNotFoundError:
        print(f"File {filename} not found")
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred: {e}")
        sys.exit(1)

        
def main():
    
    if len(sys.argv) < 3:
        print("Incorrect number of arguments")
        print("Usage: ccwc [option] [file]")
        sys.exit(1)    
    
    option = sys.argv[1]
    filename = sys.argv[2]
                  
    match option:
        case '-c':
            content = readEntireFile(filename, 'rb')
            byteCount = len(content)
            print(f"{byteCount} {filename}")
            
        case '-l':
            content = openFile(filename)
            lineCount = sum(1 for _ in content);
            print(f"{lineCount} {filename}")           
            

if __name__ == "__main__":
    main()