#!/usr/bin/env python3
import sys

def main():
    
    if len(sys.argv) < 3:
        print("Incorrect number of arguments")
        print("Usage: ccwc [option] [file]")
        sys.exit(1)    
    
    option = sys.argv[1]
    filename = sys.argv[2]
    
    if option != '-c':
        print("Invalid option")
        sys.exit(1)
        
    try:
        with open(filename, "rb") as file:
            content = file.read()
            byteCount = len(content)
                
        print(f"{byteCount} {filename}")
        
        
    except FileNotFoundError:
        print(f"File {filename} not found")
        sys.exit(1)
        
    except Exception as e:
        print(f"An error occurred: {e}")
        sys.exit(1)
    
    

if __name__ == "__main__":
    main()